openapi: 3.0.1
info:
  title: CRUD AIP
  description: 'This is a Simple API Restful'
  version: 1.0.0
servers:
  - url: http://localhost:5000

tags:
  - name: user
    description: Operations about user

paths:
  /user/register:
    post:
      tags:
        - user
      summary: Register User
      produces:
        - application/json
      consumes:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                  refresh_token:
                    type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /user/login:
    post:
      tags:
        - user
      summary: Login with username and password
      produces:
        - application/json
      consumes:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
                  refresh_token:
                    type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /user/info:
    get:
      tags:
        - user
      security:
        - ApiKeyAuth: []
      summary: Get info of user
      produces:
        - application/json
      consumes:
        - application/json
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      fullName:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                      role:
                        type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

    put:
      tags:
        - user
      security:
        - ApiKeyAuth: []
      summary: Update info of user
      produces:
        - application/json
      consumes:
        - application/json
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                fullName:
                  type: string
        required: true
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /user/logout:
    get:
      tags:
        - user
      summary: Logs out current logged with delete cookie
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /user/refresh_token:
    get:
      tags:
        - user
      security:
        - ApiKeyAuth: []
      summary: Get refresh_token of user with access_token
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      iat:
                        type: integer
                      exp:
                        type: integer
                  access_token:
                    type: string
        400:
          description: Bad request
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
        500:
          description: Internal server error
          content: {}

  /user/all:
    get:
      tags:
        - user
      security:
        - ApiKeyAuth: []
      summary: Get all users
      parameters:
        - in: query
          name: _page
          schema:
            type: integer
          description: page number
        - in: query
          name: _limit
          schema:
            type: integer
          description: limit user in page
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        username:
                          type: string
                        fullName:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                        role:
                          type: string
                  pagination:
                    type: object
                    properties:
                      _total_User:
                        type: integer
                      _page:
                        type: integer
                      _total_Page:
                        type: integer
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

  /user/{id}:
    delete:
      tags:
        - user
      security:
        - ApiKeyAuth: []
      summary: Delete user
      description: This can only be done by the logged in admin.
      parameters:
        - name: id
          in: path
          description: The id that needs to be deleted
          required: true
          schema:
            type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string
        500:
          description: Error from server
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  status:
                    type: string

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        fullName:
          type: string
        password:
          type: string
      xml:
        name: User
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
security:
  - cookieAuth: []
